---
---
version: '3.5'

networks:
  default:
    driver: bridge

services:
  cubicsdr:
    user: "1000:1000"
    image: registry.tunguska.cc/cubicsdr
    container_name: cubicsdr
    build:
      context: ./cubicsdr/
      dockerfile: Dockerfile
      args:
        ARCH: amd64
        DEBIANVERSION: bookworm
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
      - "/run/user/1000/pulse/native:/run/user/1000/pulse/native"
      - "/var/run/dbus:/var/run/dbus"
      - "/var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    network_mode: host
