---
version: '3.3'

services:
  cubicsdr:
    #image: registry.tunguska.cc/cubicsdr
    image: ghcr.io/tunguskacc/cubicsdr
    container_name: cubicsdr
    environment:
      DISPLAY: ${DISPLAY}
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix"
      - "$HOME/.Xauthority:/root/.Xauthority:rw"
    network_mode: host
