---

- name: Setup RTL SDR
  hosts: devserver
  become: yes
  become_user: root
  become_method: sudo
  vars:
    rtl_server_packages:
      - wget
      - cmake
      - build-essential
      - rtl-sdr
      - avahi-daemon
      - libavahi-client-dev
      - soapysdr0.8-module-rtlsdr
      - soapyremote-server
      - dump1090-mutability

  tasks:
  - name: Install apt packages
    package:
      state: latest
      install_recommends: no
      update_cache: yes
      autoclean: yes
       autoremove: yes
      name: "{{ rtl_server_packages }}"



